# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

platform:
  - x86
  - x64

environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run build:win

# Don't actually build.
build: off

cache:
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json # npm cache
  - node_modules -> package.json                                # local npm modules